TRI_LAYER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGB_MATRIX_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

#Convert for RP2040
CONVERT_TO=promicro_rp2040
